name: Build RetroED WZ+
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  RetroED-WZ-Plus_Windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        cache: true
    - name: Download Jom
      run: |
        Invoke-WebRequest http://download.qt.io/official_releases/jom/jom.zip -OutFile "jom.zip"
        mkdir build
        Expand-Archive -Path jom.zip -DestinationPath build
    - name: Run versiongen
      working-directory: RetroEDv2
      run: |
        py -m pip install pytz
        py versiongen.py $Env:GITHUB_SHA
    - name: Build RetroED WZ+ Windows
      working-directory: build
      run: |
        qmake ../RetroEDv2/RetroEDv2.pro -spec win32-msvc -config release "CONFIG+=qtquickcompiler"
        ./jom -j4
    - name: Move Artifacts
      run: |
        move build/release/RetroED.exe build/release/deploy/RetroED.exe
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RetroED-WZ-Plus_Windows
        path: build/release/deploy

  RetroED-WZ-Plus_Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        cache: true
    - name: Install pytz
      run: |
        pip install pytz
    - name: Install Dependancies
      run: |
        sudo apt install build-essential libqt5svg5-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools python3-pip
    - name: Build RetroED WZ+ Linux
      run: |
        cd RetroEDv2
        python3 versiongen.py
        mkdir build
        qmake -o build RetroEDv2.pro
        cd build
        make -j$(nproc)
    - name: Move Artifacts
      run: |
        mkdir artifacts
        mv ./RetroEDv2/build/RetroED ./artifacts
        tar -czvf linux.tar.gz -C ./artifacts .
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RetroED-WZ-Plus_Linux
        path: artifacts
